apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: database
    app: mysql
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
